const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const months=['فروردین','اردیبهشت','خرداد','تیر','مرداد','شهریور','مهر','آبان','آذر','دی','بهمن','اسفند'];
const week=['یکشنبه','دوشنبه','سه‌شنبه','چهارشنبه','پنجشنبه','جمعه','شنبه'];
const uid=()=>Math.random().toString(36).slice(2,10);
const faDigits='۰۱۲۳۴۵۶۷۸۹', arDigits='٠١٢٣٤٥٦٧٨٩';
const latinDigits=s=>String(s??'').replace(/[۰-۹]/g,d=>faDigits.indexOf(d)).replace(/[٠-٩]/g,d=>arDigits.indexOf(d));
const escAttr=s=>String(s??'').replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/</g,'&lt;');
function escHtml(s){const d=document.createElement('div');d.textContent=s??'';return d.innerHTML;}
function parseDays(s){const out=new Set();latinDigits(s).split(/[،,;\s]+/).filter(Boolean).forEach(t=>{const m=t.match(/^(\d+)\s*[-–—]\s*(\d+)$/);if(m){let a=+m[1],b=+m[2];if(a>b)[a,b]=[b,a];for(let d=a;d<=b;d++)out.add(d);}else{const n=parseInt(t);if(Number.isFinite(n))out.add(n);}});return [...out].sort((a,b)=>a-b);}
const splitNames=s=>[...new Set(String(s||'').split(/\s*(?:,|;|\/|&|\+|\n|،|\s+و\s+)\s*/).map(x=>x.trim()).filter(Boolean))];
const parseList=s=>[...new Set(String(s||'').split(/[،,;]+/).map(x=>x.trim()).filter(Boolean))];
const truthy=v=>['1','true','yes','y','بله','بلی','آره','مجاز'].includes(latinDigits(v).trim().toLowerCase());
const clampWeight=v=>Math.max(0,Math.min(100,Number(v)||0));
const DEFAULT_WEIGHTS={unavailable:100,preferred:50,together:75,avoid:50,morning:50};
const PRIORITY_KEYS=['unavailable','preferred','together','avoid','morning'];
let importedRows=null, externalRows=null, externalReport=null, lastPenalty=null, selectedPeople=new Set(), selectedCalendarDay=1;

function defaultShiftList(){return [
  {id:uid(),name:'اورژانس مردان',mainSlots:2,coverSlots:0,type:'general',morningRisk:true,startDay:1,endDay:31},
  {id:uid(),name:'اورژانس زنان',mainSlots:2,coverSlots:0,type:'general',morningRisk:true,startDay:1,endDay:31},
  {id:uid(),name:'داخلی ۱',mainSlots:2,coverSlots:0,type:'general',morningRisk:true,startDay:1,endDay:31},
  {id:uid(),name:'داخلی ۲',mainSlots:2,coverSlots:0,type:'general',morningRisk:true,startDay:1,endDay:31},
  {id:uid(),name:'انکولوژی',mainSlots:1,coverSlots:0,type:'general',morningRisk:false,startDay:1,endDay:31}
];}
function newPerson(p={}){return {
  id:p.id||uid(),name:p.name||'',active:p.active!==false,targetShifts:Number(p.targetShifts||0),targetHolidays:Number(p.targetHolidays||0),
  allow48:Boolean(p.allow48),unavailableDays:p.unavailableDays||[],preferredDays:p.preferredDays||[],togetherIds:p.togetherIds||[],avoidIds:p.avoidIds||[],
  allowedShiftIds:p.allowedShiftIds||[],maxConsecutiveDays:Number(p.maxConsecutiveDays||0),previousMorning:Number(p.previousMorning||0),previousShifts:Number(p.previousShifts||0),previousHolidays:Number(p.previousHolidays||0),
  startDay:Number(p.startDay||1),endDay:Number(p.endDay||31),
  ruleWeights:Object.fromEntries(PRIORITY_KEYS.map(k=>[k,p.ruleWeights?.[k]===null||p.ruleWeights?.[k]===undefined?null:clampWeight(p.ruleWeights[k])]))
};}
function fantasyPeople(){
  const names=['آرمان آذرخش','نیلا شباهنگ','سام سپهرافزا','رها ماه‌آیین','کیان مهرآوا','آوا نیک‌پی','بردیا سپهرزاد','هلیا نورافروز','پارسا شب‌تاب','ترانه ماهور','آریو مهرگان','دلارا روشن‌دل','رادین آفتاب‌فر','سها باران‌نژاد','دانیال مهرتاب','آیلین سپندار','کاوه نیلگون','مانا فرهمهر'];
  const ps=names.map((name,i)=>newPerson({name,targetShifts:7+(i%4===0?1:0),targetHolidays:i%5===0?2:1,unavailableDays:[((i*3)%27)+1],previousMorning:i%5,previousShifts:6+(i%3),previousHolidays:i%2}));
  for(let i=0;i+1<ps.length;i+=6){ps[i].togetherIds=[ps[i+1].id];ps[i+1].togetherIds=[ps[i].id];}
  for(let i=2;i+1<ps.length;i+=7){ps[i].avoidIds=[ps[i+1].id];ps[i+1].avoidIds=[ps[i].id];}
  return ps;
}
function defaultState(){return {version:'1.1',mode:'simple',year:1405,month:5,periodStart:1,periodEnd:31,simpleDailyPeople:2,fridaysHoliday:true,calendarMode:'jalali',manualDays:31,manualStartWeek:6,holidays:[],nonHolidays:[],holidayEvents:{},dayConfig:{},weeklyMorning:{},globalRuleWeights:{...DEFAULT_WEIGHTS},people:fantasyPeople(),shifts:defaultShiftList(),assignments:[],seededDemo:true};}
function migrateState(s){
  if(!s)return defaultState();const out=defaultState();
  out.mode=s.mode||'advanced';out.year=Number(s.year||1405);out.month=Number(s.month||5);out.periodStart=Number(s.periodStart||1);out.periodEnd=Number(s.periodEnd||31);out.simpleDailyPeople=Number(s.simpleDailyPeople||2);
  out.fridaysHoliday=s.fridaysHoliday!==false;out.calendarMode=s.calendarMode||'jalali';out.manualDays=Number(s.manualDays||31);out.manualStartWeek=Number.isFinite(Number(s.manualStartWeek))?Number(s.manualStartWeek):6;
  out.holidays=s.holidays||[];out.nonHolidays=s.nonHolidays||[];out.holidayEvents=s.holidayEvents||{};out.dayConfig=s.dayConfig||{};out.weeklyMorning=s.weeklyMorning||{};out.globalRuleWeights={...DEFAULT_WEIGHTS,...(s.globalRuleWeights||{})};
  out.shifts=(s.shifts?.length?s.shifts:defaultShiftList()).map(x=>({id:x.id||uid(),name:x.name||'',mainSlots:Math.max(0,Number(x.mainSlots??x.slots??1)),coverSlots:Math.max(0,Number(x.coverSlots??0)),type:x.type||'general',morningRisk:Boolean(x.morningRisk),startDay:Number(x.startDay||1),endDay:Number(x.endDay||31)}));
  out.people=(s.people||[]).map(p=>newPerson({...p,allow48:p.allow48!==undefined?p.allow48:(p.noConsecutive===false)}));out.assignments=s.assignments||[];out.seededDemo=Boolean(s.seededDemo);return out;
}
function load(){try{for(const key of ['keshikYarV11','keshikPlannerV1Milad98','keshikPlannerV2','keshikPlannerV1']){const raw=localStorage.getItem(key);if(raw)return migrateState(JSON.parse(raw));}}catch(e){console.warn(e);}return null;}
let state=load()||defaultState();
function save(){localStorage.setItem('keshikYarV11',JSON.stringify(state));renderDashboard();}
function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2400);}
async function download(blob,name){
  if(window.KeshikNativeSave && window.Capacitor?.isNativePlatform?.()){
    try{await window.KeshikNativeSave(blob,name);return;}
    catch(err){console.error('Native file save failed:',err);try{toast('ذخیره مستقیم انجام نشد؛ روش معمول را امتحان می‌کنیم');}catch(_e){}}
  }
  const a=document.createElement('a');
  const url=URL.createObjectURL(blob);
  a.href=url;a.download=name;a.style.display='none';
  document.body.appendChild(a);a.click();a.remove();
  setTimeout(()=>URL.revokeObjectURL(url),3000);
}

months.forEach((m,i)=>$('#jm').insertAdjacentHTML('beforeend',`<option value="${i+1}">${m}</option>`));
week.forEach((w,i)=>$('#manualStartWeek').insertAdjacentHTML('beforeend',`<option value="${i}">${w}</option>`));

function daysInMonth(){return state.calendarMode==='manual'?Math.max(28,Math.min(31,Number(state.manualDays||31))):Jalali.monthLength(state.year,state.month);}
function periodBounds(){const n=daysInMonth(),a=Math.max(1,Math.min(n,Number(state.periodStart||1))),b=Math.max(a,Math.min(n,Number(state.periodEnd||n)));return {start:a,end:b};}
function activeDays(){const {start,end}=periodBounds();return Array.from({length:end-start+1},(_,i)=>start+i);}
function weekdayForDay(d){return state.calendarMode==='manual'?(Number(state.manualStartWeek||0)+d-1)%7:Jalali.weekday(state.year,state.month,d);}
function weekdaysArray(){const arr=[];for(let d=1;d<=daysInMonth();d++)arr[d]=weekdayForDay(d);return arr;}
function effectiveHolidays(){const s=new Set((state.holidays||[]).filter(d=>d>=1&&d<=daysInMonth())),off=new Set(state.nonHolidays||[]);if(state.fridaysHoliday)for(let d=1;d<=daysInMonth();d++)if(weekdayForDay(d)===5&&!off.has(d))s.add(d);for(const d of off)s.delete(d);return [...s].sort((a,b)=>a-b);}
function getDayConfig(day){return state.dayConfig?.[day]||state.dayConfig?.[String(day)]||{};}
function ensureDayConfig(day){state.dayConfig??={};state.dayConfig[day]??={mainSlots:{},coverSlots:{},morningByShift:{}};state.dayConfig[day].mainSlots??={};state.dayConfig[day].coverSlots??={};state.dayConfig[day].morningByShift??={};return state.dayConfig[day];}
function shiftActive(s,d){const {start,end}=periodBounds();return d>=Math.max(start,Number(s.startDay||1))&&d<=Math.min(end,Number(s.endDay||daysInMonth()));}
function mainCount(d,s){if(!shiftActive(s,d))return 0;const v=getDayConfig(d)?.mainSlots?.[s.id];return v!==undefined&&v!==null&&v!==''?Math.max(0,Number(v)||0):Math.max(0,Number(s.mainSlots||0));}
function coverCount(d,s){if(!shiftActive(s,d))return 0;const v=getDayConfig(d)?.coverSlots?.[s.id];return v!==undefined&&v!==null&&v!==''?Math.max(0,Number(v)||0):Math.max(0,Number(s.coverSlots||0));}
function simpleCount(d){const v=getDayConfig(d)?.simpleSlots;return v!==undefined&&v!==null&&v!==''?Math.max(0,Number(v)||0):Math.max(1,Number(state.simpleDailyPeople||2));}
function currentShifts(){return state.mode==='simple'?[{id:'simple',name:'کشیک',mainSlots:Number(state.simpleDailyPeople||2),coverSlots:0,type:'general',morningRisk:false,startDay:periodBounds().start,endDay:periodBounds().end}]:state.shifts;}
function totalSlots(){let n=0;for(const d of activeDays()){if(state.mode==='simple')n+=simpleCount(d);else for(const s of state.shifts)n+=mainCount(d,s)+coverCount(d,s);}return n;}
function effectiveSectionMorning(s,d){const dc=getDayConfig(d),direct=dc?.morningByShift?.[s.id];if(typeof direct==='boolean')return direct;const weekly=state.weeklyMorning?.[weekdayForDay(d)]?.[s.id];if(typeof weekly==='boolean')return weekly;return Boolean(s.morningRisk);}

function setMode(mode){if(!['simple','advanced'].includes(mode))return;state.mode=mode;state.assignments=[];lastPenalty=null;save();applyModeUI();renderAll();toast(mode==='simple'?'حالت ساده فعال شد':'حالت پیشرفته فعال شد');}
function applyModeUI(){
  const adv=state.mode==='advanced';$('#modeBadge').textContent=adv?'پیشرفته':'ساده';$$('[data-advanced-only]').forEach(el=>el.classList.toggle('mode-hidden',!adv));$$('[data-advanced-field]').forEach(el=>el.classList.toggle('mode-hidden',!adv));$$('[data-simple-only]').forEach(el=>el.classList.toggle('mode-hidden',adv));$$('[data-set-mode]').forEach(b=>b.classList.toggle('selected-mode',b.dataset.setMode===state.mode));
  $('#workflowSteps').innerHTML=adv?'<span>۱. Excel یا اسامی</span><span>۲. محدودیت‌ها</span><span>۳. بخش‌ها</span><span>۴. روزها</span><span>۵. چیدن</span><span>۶. تحلیل</span>':'<span>۱. اسامی</span><span>۲. محدودیت/جفت</span><span>۳. روزها</span><span>۴. چیدن</span><span>۵. بررسی</span>';
  const active=$('.section.active');if(active?.hasAttribute('data-advanced-only')&&!adv)go('dashboard');
}
$$('[data-set-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.setMode));
function go(page){const target=$('#'+page);if(!target||(state.mode!=='advanced'&&target.hasAttribute('data-advanced-only')))return;$$('.section').forEach(x=>x.classList.toggle('active',x.id===page));$$('.nav button').forEach(x=>x.classList.toggle('active',x.dataset.page===page));const b=$(`.nav button[data-page="${page}"]`);$('#pageTitle').textContent=b?.textContent||'';if(page==='people')renderPeople();if(page==='shifts')renderShifts();if(page==='calendar')renderCalendar();if(page==='generate')renderGlobalPriorities();if(page==='schedule')renderSchedule();if(page==='analysis')renderAnalysis();if(page==='extras')window.KeshikExtras?.render?.();}
$$('.nav button').forEach(b=>b.onclick=()=>go(b.dataset.page));$$('[data-page-jump]').forEach(b=>b.onclick=()=>go(b.dataset.pageJump));

function normalizePeopleLinks(){const ids=new Set(state.people.map(x=>x.id));state.globalRuleWeights={...DEFAULT_WEIGHTS,...(state.globalRuleWeights||{})};for(const p of state.people){p.togetherIds=(p.togetherIds||[]).filter(id=>ids.has(id)&&id!==p.id);p.avoidIds=(p.avoidIds||[]).filter(id=>ids.has(id)&&id!==p.id);p.allowedShiftIds=(p.allowedShiftIds||[]).filter(id=>state.shifts.some(s=>s.id===id));p.ruleWeights??={};for(const k of PRIORITY_KEYS)p.ruleWeights[k]=p.ruleWeights[k]===null||p.ruleWeights[k]===undefined?null:clampWeight(p.ruleWeights[k]);}}
function priorityLabel(x){return x===0?'بی‌اهمیت':x===25?'کم':x===50?'متوسط':x===75?'زیاد':'خط قرمز';}
function weightOptions(v,inherit=false,globalValue=50){let h=inherit?`<option value="inherit" ${v===null||v===undefined?'selected':''}>همان تنظیم کلی (${globalValue})</option>`:'';return h+[0,25,50,75,100].map(x=>`<option value="${x}" ${Number(v)===x?'selected':''}>${x} — ${priorityLabel(x)}</option>`).join('');}
function renderGlobalPriorities(){const boxes=$$('[data-global-priorities]');const items=[['unavailable','روز ممنوع'],['preferred','روز ترجیحی'],['together','جفت'],['avoid','جفت‌نشدن'],['morning','مورنینگ']];for(const box of boxes){box.innerHTML=items.map(([k,t])=>`<div class="field"><label>${t}</label><select data-global-weight="${k}">${weightOptions(clampWeight(state.globalRuleWeights?.[k]??DEFAULT_WEIGHTS[k]))}</select></div>`).join('');box.querySelectorAll('[data-global-weight]').forEach(sel=>sel.onchange=()=>{state.globalRuleWeights[sel.dataset.globalWeight]=clampWeight(sel.value);state.assignments=[];save();renderGlobalPriorities();renderPeople();});}}
function relationBox(p,key,title){const selected=p[key]||[],others=state.people.filter(x=>x.id!==p.id);return `<div class="relation-box" data-relbox="${key}"><div class="rel-title">${title}</div><div class="chips">${selected.map(id=>{const q=state.people.find(x=>x.id===id);return q?`<span class="chip">${escHtml(q.name||'بدون نام')} <button type="button" data-remove-rel="${id}">×</button></span>`:'';}).join('')||'<span class="muted">کسی انتخاب نشده</span>'}</div><details><summary class="muted">انتخاب افراد</summary><div class="pick-list">${others.map(q=>`<label><input type="checkbox" data-rel="${key}" value="${q.id}" ${selected.includes(q.id)?'checked':''}> ${escHtml(q.name||'بدون نام')}</label>`).join('')||'<span class="muted">ابتدا فرد دیگری اضافه کن</span>'}</div></details></div>`;}
function shiftPicker(p){const selected=p.allowedShiftIds||[];return `<div class="relation-box"><div class="rel-title">بخش‌های مجاز <span class="muted">(خالی = همه)</span></div><div class="chips">${selected.map(id=>{const s=state.shifts.find(x=>x.id===id);return s?`<span class="chip">${escHtml(s.name)} <button type="button" data-remove-shift="${id}">×</button></span>`:'';}).join('')||'<span class="muted">همه بخش‌ها مجازند</span>'}</div><details><summary class="muted">انتخاب بخش‌ها</summary><div class="pick-list">${state.shifts.map(s=>`<label><input type="checkbox" data-shiftpick value="${s.id}" ${selected.includes(s.id)?'checked':''}> ${escHtml(s.name)}</label>`).join('')}</div></details></div>`;}
function priorityBox(p){const items=[['unavailable','روز ممنوع'],['preferred','روز ترجیحی'],['together','جفت'],['avoid','جفت‌نشدن'],['morning','مورنینگ']];return `<div class="priority-box"><div class="rel-title">تنظیم مخصوص این فرد</div>${items.map(([k,t])=>`<div class="priority-row"><b>${t}</b><select data-weight="${k}">${weightOptions(p.ruleWeights?.[k],true,clampWeight(state.globalRuleWeights?.[k]??DEFAULT_WEIGHTS[k]))}</select></div>`).join('')}</div>`;}
function addPerson(p={}){state.seededDemo=false;state.people.unshift(newPerson(p));state.assignments=[];save();renderPeople();requestAnimationFrame(()=>{const card=$('#peopleCards .person-card');if(card){const sticky=document.querySelector('.sidebar');const offset=(window.innerWidth<=900?(sticky?.getBoundingClientRect().height||110)+14:18);const top=card.getBoundingClientRect().top+window.scrollY-offset;window.scrollTo({top:Math.max(0,top),behavior:'smooth'});setTimeout(()=>card.querySelector('[data-k="name"]')?.focus({preventScroll:true}),260);}});}
$('#addPerson').onclick=()=>addPerson();
$('#clearPeople').onclick=()=>{if(confirm('همه اسامی پاک شوند؟')){state.people=[];state.assignments=[];state.seededDemo=false;selectedPeople.clear();save();renderPeople();}};
$('#addDemo').onclick=()=>{if(state.people.length&&!confirm('لیست فعلی با اسامی نمونه جایگزین شود؟'))return;state.people=fantasyPeople();state.assignments=[];state.seededDemo=true;selectedPeople.clear();save();renderPeople();};
$('#selectAllPeople').onclick=()=>{state.people.forEach(p=>selectedPeople.add(p.id));renderPeople();};$('#clearSelection').onclick=()=>{selectedPeople.clear();renderPeople();};
$('#deleteSelected').onclick=()=>{if(!selectedPeople.size)return toast('کسی انتخاب نشده');if(!confirm(`${selectedPeople.size} نفر حذف شوند؟`))return;state.people=state.people.filter(p=>!selectedPeople.has(p.id));selectedPeople.clear();normalizePeopleLinks();state.assignments=[];save();renderPeople();};
function renderPeople(){
  normalizePeopleLinks();const box=$('#peopleCards');box.innerHTML='';const adv=state.mode==='advanced';
  state.people.forEach((p,i)=>{const card=document.createElement('div');card.className='person-card'+(selectedPeople.has(p.id)?' selected':'');
    const headAdvanced=adv?`<div class="field"><label>تعداد کشیک</label><input type="number" min="0" data-k="targetShifts" value="${p.targetShifts||''}" placeholder="مثلاً 7"></div><div class="field"><label>تعداد کشیک تعطیل</label><input type="number" min="0" data-k="targetHolidays" value="${p.targetHolidays||''}" placeholder="مثلاً 1"></div><div class="field"><label>دو روز پشت‌سرهم</label><div class="check-line"><input type="checkbox" data-k="allow48" ${p.allow48?'checked':''}><span>${p.allow48?'مجاز':'ممنوع'}</span></div></div>`:'';
    const simpleBody=`<div class="detail-grid"><div class="field"><label>روزهای ممنوع</label><input data-k="unavailableDays" value="${(p.unavailableDays||[]).join(', ')}" placeholder="3,7,12-15"></div>${relationBox(p,'togetherIds','جفت / بهتر است با این افراد باشد')}${relationBox(p,'avoidIds','نباشد با / بهتر است هم‌روز نباشند')}</div>`;
    const advancedBody=`<div class="detail-grid"><div class="field"><label>روزهای ممنوع / مرخصی</label><input data-k="unavailableDays" value="${(p.unavailableDays||[]).join(', ')}" placeholder="3,7,12-15"></div><div class="field"><label>روزهای ترجیحی</label><input data-k="preferredDays" value="${(p.preferredDays||[]).join(', ')}" placeholder="5,20"></div><div class="field"><label>از روز</label><input type="number" min="1" max="31" data-k="startDay" value="${p.startDay||1}"></div><div class="field"><label>تا روز</label><input type="number" min="1" max="31" data-k="endDay" value="${p.endDay||31}"></div><div class="field"><label>حداکثر روز پشت‌سرهم (0 = خودکار)</label><input type="number" min="0" data-k="maxConsecutiveDays" value="${p.maxConsecutiveDays||''}"></div><div class="field"><label>مورنینگ ماه‌های قبل</label><input type="number" min="0" data-k="previousMorning" value="${p.previousMorning||''}"></div><div class="field"><label>کشیک ماه‌های قبل</label><input type="number" min="0" data-k="previousShifts" value="${p.previousShifts||''}"></div><div class="field"><label>کشیک تعطیل ماه‌های قبل</label><input type="number" min="0" data-k="previousHolidays" value="${p.previousHolidays||''}"></div><div class="field"><label>وضعیت</label><div class="check-line"><input type="checkbox" data-k="active" ${p.active?'checked':''}><span>در چیدمان باشد</span></div></div>${relationBox(p,'togetherIds','جفت / بهتر است با این افراد باشد')}${relationBox(p,'avoidIds','نباشد با / بهتر است هم‌روز نباشند')}${shiftPicker(p)}</div>${priorityBox(p)}`;
    card.innerHTML=`<div class="person-head"><div class="select-box"><input type="checkbox" data-select-person ${selectedPeople.has(p.id)?'checked':''}></div><div class="field name-field"><label>نام</label><input data-k="name" value="${escAttr(p.name)}" placeholder="نام و نام خانوادگی"></div>${headAdvanced}<button class="btn danger sm" data-del>حذف</button></div><details class="person-details"><summary>${adv?'روزها، روابط و تنظیمات بیشتر':'روزهای ممنوع و رابطه با بقیه'}</summary>${adv?advancedBody:simpleBody}</details>`;
    card.querySelector('[data-select-person]').onchange=e=>{e.target.checked?selectedPeople.add(p.id):selectedPeople.delete(p.id);renderPeople();};card.querySelector('[data-del]').onclick=()=>{state.people.splice(i,1);selectedPeople.delete(p.id);normalizePeopleLinks();state.assignments=[];save();renderPeople();};
    card.querySelectorAll('[data-k]').forEach(inp=>inp.onchange=()=>{const k=inp.dataset.k;if(k==='name')p.name=inp.value.trim();else if(['allow48','active'].includes(k))p[k]=inp.checked;else if(['unavailableDays','preferredDays'].includes(k))p[k]=parseDays(inp.value);else p[k]=Number(inp.value||0);state.seededDemo=false;state.assignments=[];save();if(['name','allow48'].includes(k))renderPeople();});
    card.querySelectorAll('[data-weight]').forEach(sel=>sel.onchange=()=>{p.ruleWeights[sel.dataset.weight]=sel.value==='inherit'?null:clampWeight(sel.value);state.assignments=[];save();renderPeople();});
    card.querySelectorAll('[data-rel]').forEach(inp=>inp.onchange=()=>{const k=inp.dataset.rel,set=new Set(p[k]||[]);inp.checked?set.add(inp.value):set.delete(inp.value);p[k]=[...set];state.assignments=[];save();renderPeople();});
    card.querySelectorAll('[data-remove-rel]').forEach(btn=>btn.onclick=()=>{const k=btn.closest('[data-relbox]').dataset.relbox;p[k]=(p[k]||[]).filter(id=>id!==btn.dataset.removeRel);state.assignments=[];save();renderPeople();});
    card.querySelectorAll('[data-shiftpick]').forEach(inp=>inp.onchange=()=>{const set=new Set(p.allowedShiftIds||[]);inp.checked?set.add(inp.value):set.delete(inp.value);p.allowedShiftIds=[...set];state.assignments=[];save();renderPeople();});
    card.querySelectorAll('[data-remove-shift]').forEach(btn=>btn.onclick=()=>{p.allowedShiftIds=(p.allowedShiftIds||[]).filter(id=>id!==btn.dataset.removeShift);state.assignments=[];save();renderPeople();});box.appendChild(card);
  });$('#selectionCount').textContent=`${selectedPeople.size} نفر انتخاب شده`;
}

function clearShiftOverrides(id){for(const cfg of Object.values(state.dayConfig||{})){delete cfg?.mainSlots?.[id];delete cfg?.coverSlots?.[id];delete cfg?.morningByShift?.[id];}for(const wd of Object.values(state.weeklyMorning||{}))if(wd)delete wd[id];}
$('#addShift').onclick=()=>{state.shifts.push({id:uid(),name:'بخش جدید',mainSlots:1,coverSlots:0,type:'general',morningRisk:false,startDay:periodBounds().start,endDay:periodBounds().end});state.assignments=[];save();renderShifts();renderPeople();renderCalendar();};
$('#defaultShifts').onclick=()=>{if(!confirm('بخش‌های فعلی با قالب نمونه جایگزین شوند؟'))return;state.shifts=defaultShiftList();state.dayConfig={};state.weeklyMorning={};state.assignments=[];normalizePeopleLinks();save();renderShifts();renderPeople();renderCalendar();};
function renderShifts(){
  const b=$('#shiftBody');b.innerHTML='';state.shifts.forEach((s,i)=>{const tr=document.createElement('tr');tr.innerHTML=`<td><input value="${escAttr(s.name)}"></td><td><input type="number" min="0" max="30" value="${s.mainSlots}"></td><td><input type="number" min="0" max="30" value="${s.coverSlots}"></td><td><select><option value="general">عمومی</option><option value="day">روز</option><option value="night">شب</option><option value="24h">۲۴ ساعته</option></select></td><td><input type="checkbox" ${s.morningRisk?'checked':''}></td><td><input type="number" min="1" max="31" value="${s.startDay||1}"></td><td><input type="number" min="1" max="31" value="${s.endDay||31}"></td><td><button class="btn danger sm">حذف</button></td>`;const ins=tr.querySelectorAll('input'),sel=tr.querySelector('select');sel.value=s.type||'general';
    ins[0].onchange=()=>{s.name=ins[0].value.trim();state.assignments=[];save();renderPeople();renderCalendar();};ins[1].onchange=()=>{s.mainSlots=Math.max(0,Number(ins[1].value)||0);state.assignments=[];save();renderCalendar();};ins[2].onchange=()=>{s.coverSlots=Math.max(0,Number(ins[2].value)||0);state.assignments=[];save();renderCalendar();};sel.onchange=()=>{s.type=sel.value;state.assignments=[];save();};ins[3].onchange=()=>{s.morningRisk=ins[3].checked;state.assignments=[];save();renderWeeklyMorning();renderCalendar();};ins[4].onchange=()=>{s.startDay=Math.max(1,Number(ins[4].value)||1);state.assignments=[];save();renderCalendar();};ins[5].onchange=()=>{s.endDay=Math.max(1,Number(ins[5].value)||31);state.assignments=[];save();renderCalendar();};tr.querySelector('button').onclick=()=>{clearShiftOverrides(s.id);state.shifts.splice(i,1);state.assignments=[];normalizePeopleLinks();save();renderShifts();renderPeople();renderCalendar();};b.appendChild(tr);
  });renderWeeklyMorning();
}
function morningOverrideOptions(value){return `<option value="inherit" ${value===undefined?'selected':''}>طبق پیش‌فرض بخش</option><option value="1" ${value===true?'selected':''}>مورنینگ دارد</option><option value="0" ${value===false?'selected':''}>مورنینگ ندارد</option>`;}
function renderWeeklyMorning(){const box=$('#weeklyMorningGrid');if(!box)return;let h='<table><thead><tr><th>بخش</th>'+week.map(w=>`<th>${w}</th>`).join('')+'</tr></thead><tbody>';for(const s of state.shifts){h+=`<tr><td>${escHtml(s.name)}</td>`;for(let wd=0;wd<7;wd++){const val=state.weeklyMorning?.[wd]?.[s.id];h+=`<td><select data-week-morning="${wd}:${s.id}">${morningOverrideOptions(val)}</select></td>`;}h+='</tr>'; }h+='</tbody></table>';box.innerHTML=h;box.querySelectorAll('[data-week-morning]').forEach(sel=>sel.onchange=()=>{const [wd,id]=sel.dataset.weekMorning.split(':');state.weeklyMorning[wd]??={};if(sel.value==='inherit')delete state.weeklyMorning[wd][id];else state.weeklyMorning[wd][id]=sel.value==='1';state.assignments=[];save();renderCalendar();});}

function renderCalendar(){
  const n=daysInMonth(),hol=new Set(effectiveHolidays()),{start,end}=periodBounds();selectedCalendarDay=Math.min(Math.max(1,selectedCalendarDay),n);$('#manualCalendarBox').classList.toggle('hidden',state.calendarMode!=='manual');$('#manualDays').value=state.manualDays;$('#manualStartWeek').value=state.manualStartWeek;$('#manualHolidayDays').value=(state.holidays||[]).join(', ');$('#periodStart').value=start;$('#periodEnd').value=end;$('#simpleDailyPeople').value=state.simpleDailyPeople;
  const grid=$('#calendarGrid');grid.innerHTML='';for(let d=1;d<=n;d++){const wd=weekdayForDay(d),cfg=getDayConfig(d),event=(state.holidayEvents||{})[d]||'',inPeriod=d>=start&&d<=end,el=document.createElement('div');el.className='day'+(hol.has(d)?' holiday':'')+(wd===5?' friday':'')+(d===selectedCalendarDay?' selected-day':'')+(!inPeriod?' outside-period':'');const special=state.mode==='simple'?(cfg.simpleSlots!==undefined?'<span class="pill">تعداد ویژه</span>':''):(Object.keys(cfg.mainSlots||{}).length||Object.keys(cfg.coverSlots||{}).length?'<span class="pill">تعداد ویژه</span>':'');el.innerHTML=`<div class="d">${d}</div><div class="w">${week[wd]}</div><div class="day-pills">${!inPeriod?'<span class="pill">خارج بازه</span>':''}${state.mode==='advanced'&&hol.has(d)?'<span class="pill red">تعطیل</span>':''}${state.mode==='advanced'&&cfg.morningRisk?'<span class="pill gold">مورنینگ روز</span>':''}${special}</div>${event?`<div class="event">${escHtml(event)}</div>`:''}`;el.onclick=()=>{selectedCalendarDay=d;renderCalendar();};grid.appendChild(el);}renderDayEditor();
}
function renderDayEditor(){
  const box=$('#dayEditor'),d=selectedCalendarDay;if(!d||d>daysInMonth())return;const {start,end}=periodBounds(),inPeriod=d>=start&&d<=end,cfg=getDayConfig(d);if(!inPeriod){box.innerHTML=`<h3>روز ${d}</h3><div class="notice">این روز بیرون بازه چیدمان است. اگر لازم داری، بازه بالا را تغییر بده.</div>`;return;}
  if(state.mode==='simple'){
    box.innerHTML=`<h3>روز ${d} — ${week[weekdayForDay(d)]}</h3><div class="grid g2"><div class="field"><label>چند نفر این روز کشیک باشند؟</label><input id="editSimpleSlots" type="number" min="0" max="30" value="${cfg.simpleSlots===undefined?'':cfg.simpleSlots}" placeholder="پیش‌فرض: ${state.simpleDailyPeople}"></div><div class="field"><label>راهنما</label><div class="muted">خالی یعنی همان تعداد پیش‌فرض. صفر یعنی این روز کشیک نداشته باشد.</div></div></div>`;$('#editSimpleSlots').onchange=e=>{const x=ensureDayConfig(d);if(e.target.value==='')delete x.simpleSlots;else x.simpleSlots=Math.max(0,Number(e.target.value)||0);state.assignments=[];save();renderCalendar();};return;
  }
  const hol=new Set(effectiveHolidays()),event=(state.holidayEvents||{})[d]||'';
  box.innerHTML=`<h3>روز ${d} — ${week[weekdayForDay(d)]}</h3>${event?`<div class="notice">مناسبت: ${escHtml(event)}</div>`:''}<div class="grid g3 top-gap"><div class="field"><label>تعطیل</label><div class="check-line"><input id="editHoliday" type="checkbox" ${hol.has(d)?'checked':''}><span>این روز تعطیل است</span></div></div><div class="field"><label>مورنینگ خود روز</label><div class="check-line"><input id="editMorningDay" type="checkbox" ${cfg.morningRisk?'checked':''}><span>برای همه کشیک‌های این روز یک امتیاز جدا اضافه شود</span></div></div><div class="field"><label>تعداد نفرات</label><div class="muted">برای هر بخش نفر اصلی و کاور جداست.</div></div></div><div class="day-cap-grid top-gap">${state.shifts.map(s=>{const rm=cfg.mainSlots?.[s.id],rc=cfg.coverSlots?.[s.id],mo=cfg.morningByShift?.[s.id];return `<div class="day-shift-box"><b>${escHtml(s.name)}</b><div class="grid g3"><div class="field"><label>اصلی</label><input type="number" min="0" data-day-main="${s.id}" value="${rm===undefined?'':rm}" placeholder="${s.mainSlots}"></div><div class="field"><label>کاور</label><input type="number" min="0" data-day-cover="${s.id}" value="${rc===undefined?'':rc}" placeholder="${s.coverSlots}"></div><div class="field"><label>مورنینگ این بخش در این روز</label><select data-day-morning="${s.id}">${morningOverrideOptions(mo)}</select></div></div></div>`;}).join('')}</div><div class="actions top-gap"><button class="btn light" id="resetDay">برگرداندن تنظیم این روز به حالت عادی</button></div>`;
  $('#editHoliday').onchange=e=>{const manual=new Set(state.holidays||[]),off=new Set(state.nonHolidays||[]);if(e.target.checked){manual.add(d);off.delete(d);}else{manual.delete(d);off.add(d);}state.holidays=[...manual];state.nonHolidays=[...off];state.assignments=[];save();renderCalendar();};$('#editMorningDay').onchange=e=>{ensureDayConfig(d).morningRisk=e.target.checked;state.assignments=[];save();renderCalendar();};
  $$('[data-day-main]').forEach(inp=>inp.onchange=()=>{const x=ensureDayConfig(d),id=inp.dataset.dayMain;if(inp.value==='')delete x.mainSlots[id];else x.mainSlots[id]=Math.max(0,Number(inp.value)||0);state.assignments=[];save();renderCalendar();});$$('[data-day-cover]').forEach(inp=>inp.onchange=()=>{const x=ensureDayConfig(d),id=inp.dataset.dayCover;if(inp.value==='')delete x.coverSlots[id];else x.coverSlots[id]=Math.max(0,Number(inp.value)||0);state.assignments=[];save();renderCalendar();});$$('[data-day-morning]').forEach(sel=>sel.onchange=()=>{const x=ensureDayConfig(d),id=sel.dataset.dayMorning;if(sel.value==='inherit')delete x.morningByShift[id];else x.morningByShift[id]=sel.value==='1';state.assignments=[];save();renderCalendar();});
  $('#resetDay').onclick=()=>{state.dayConfig[d]={mainSlots:{},coverSlots:{},morningByShift:{}};state.assignments=[];save();renderCalendar();};
}
$('#periodStart').onchange=()=>{state.periodStart=Number($('#periodStart').value||1);state.assignments=[];save();renderCalendar();};$('#periodEnd').onchange=()=>{state.periodEnd=Number($('#periodEnd').value||daysInMonth());state.assignments=[];save();renderCalendar();};$('#simpleDailyPeople').onchange=()=>{state.simpleDailyPeople=Math.max(1,Number($('#simpleDailyPeople').value)||2);state.assignments=[];save();renderCalendar();};
$('#jy').onchange=()=>{state.year=Number($('#jy').value);state.holidays=[];state.nonHolidays=[];state.holidayEvents={};state.dayConfig={};state.assignments=[];selectedCalendarDay=1;state.periodEnd=daysInMonth();save();renderCalendar();};$('#jm').onchange=()=>{state.month=Number($('#jm').value);state.holidays=[];state.nonHolidays=[];state.holidayEvents={};state.dayConfig={};state.assignments=[];selectedCalendarDay=1;state.periodStart=1;state.periodEnd=daysInMonth();save();renderCalendar();};$('#fridaysHoliday').onchange=()=>{state.fridaysHoliday=$('#fridaysHoliday').value==='1';state.assignments=[];save();renderCalendar();};$('#calendarMode').onchange=()=>{state.calendarMode=$('#calendarMode').value;state.periodEnd=daysInMonth();state.assignments=[];save();renderCalendar();};$('#applyManualCalendar').onclick=()=>{state.manualDays=Math.max(28,Math.min(31,Number($('#manualDays').value||31)));state.manualStartWeek=Number($('#manualStartWeek').value||0);state.holidays=parseDays($('#manualHolidayDays').value).filter(d=>d<=state.manualDays);state.nonHolidays=[];state.periodEnd=Math.min(state.periodEnd,state.manualDays);state.assignments=[];save();renderCalendar();};
$('#loadOfficial').onclick=()=>{if(state.year!==1405)return toast('اطلاعات داخلی فقط برای ۱۴۰۵ است؛ برای سال دیگر دستی یا اینترنتی وارد کن');state.holidays=[...(window.IRAN_HOLIDAYS_1405[state.month]||[])];state.nonHolidays=[];state.holidayEvents={};state.assignments=[];save();renderCalendar();};$('#clearHolidays').onclick=()=>{state.holidays=[];state.nonHolidays=[];state.holidayEvents={};state.assignments=[];save();renderCalendar();};
function extractHolidayEntries(data){const found=new Map(),seen=new Set();function walk(x){if(!x||typeof x!=='object'||seen.has(x))return;seen.add(x);if(Array.isArray(x)){x.forEach(walk);return;}let day=null,holiday=false,event='';if(x.solar&&Number(x.solar.day)){day=Number(x.solar.day);holiday=x.holiday===true||x.isHoliday===true||x.is_holiday===true;event=Array.isArray(x.event)?x.event.join('، '):String(x.event||x.title||x.description||'');}else if(Number(x.day)){day=Number(x.day);holiday=x.holiday===true||x.isHoliday===true||x.is_holiday===true||x.holiday===1||String(x.holiday).toLowerCase()==='true';event=Array.isArray(x.event)?x.event.join('، '):String(x.event||x.title||x.description||'');}if(day&&holiday)found.set(day,event);Object.values(x).forEach(walk);}walk(data);return [...found].map(([day,event])=>({day,event}));}
$('#fetchHolidays').onclick=async()=>{const source=$('#holidaySource').value,status=$('#holidayStatus');status.textContent='در حال دریافت...';try{const url=source==='pnldev'?`https://pnldev.com/api/calender?year=${state.year}&month=${state.month}&holiday=true`:`https://persian-calendar-api.sajjadth.workers.dev/?year=${state.year}&month=${state.month}`;const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error();const rows=extractHolidayEntries(await r.json());if(!rows.length)throw new Error();state.holidays=[...new Set(rows.map(x=>x.day))];state.nonHolidays=[];state.holidayEvents=Object.fromEntries(rows.map(x=>[x.day,x.event]).filter(x=>x[1]));state.assignments=[];save();renderCalendar();status.textContent=`${state.holidays.length} روز تعطیل پیدا شد.`;}catch(e){status.textContent='دریافت خودکار انجام نشد. تعطیلات را دستی وارد کن.';}};
$('#holidayFile').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{let entries=[];if(f.name.toLowerCase().endsWith('.json'))entries=extractHolidayEntries(JSON.parse(await f.text()));else{const rows=(await f.text()).split(/\r?\n/).map(r=>r.split(',').map(x=>x.trim())).filter(r=>r.some(Boolean));rows.shift();entries=rows.map(r=>({day:Number(latinDigits(r[0])),event:r[1]||''})).filter(x=>x.day);}state.holidays=[...new Set(entries.map(x=>x.day))];state.holidayEvents=Object.fromEntries(entries.map(x=>[x.day,x.event]).filter(x=>x[1]));state.assignments=[];save();renderCalendar();}catch(err){alert('فایل تعطیلات خوانده نشد.');}};

function buildSolverInput(){
  const shifts=currentShifts(),dayConfig=JSON.parse(JSON.stringify(state.dayConfig||{})),people=state.people.filter(p=>p.active).map(p=>({...p,ruleWeights:{...p.ruleWeights}})),weights=state.mode==='simple'?{unavailable:100,preferred:0,together:75,avoid:75,morning:0}:{...state.globalRuleWeights};
  if(state.mode==='simple'){
    for(const d of activeDays()){dayConfig[d]??={};dayConfig[d].mainSlots={simple:simpleCount(d)};dayConfig[d].coverSlots={simple:0};dayConfig[d].morningByShift={simple:false};}
    for(const p of people){p.targetShifts=0;p.targetHolidays=0;p.preferredDays=[];p.allowedShiftIds=[];p.previousMorning=0;p.previousShifts=0;p.previousHolidays=0;p.allow48=true;p.maxConsecutiveDays=31;p.startDay=periodBounds().start;p.endDay=periodBounds().end;p.ruleWeights={unavailable:100,preferred:0,together:75,avoid:75,morning:0};}
  }
  return {people,globalRuleWeights:weights,shifts,dayConfig,weeklyMorning:state.mode==='advanced'?state.weeklyMorning:{},daysInMonth:daysInMonth(),periodStart:periodBounds().start,periodEnd:periodBounds().end,holidays:state.mode==='advanced'?effectiveHolidays():[],weekdays:weekdaysArray(),runs:Number($('#runs')?.value||28)};
}
$('#solveBtn').onclick=async()=>{const active=state.people.filter(p=>p.active);if(active.length<2)return toast('حداقل دو نفر وارد کن');if(active.some(p=>!p.name.trim()))return toast('اسم همه افراد را کامل کن');if(state.mode==='advanced'&&active.some(p=>Number(p.targetShifts||0)<=0))return toast('در حالت پیشرفته برای همه افراد تعداد کشیک را مشخص کن');if(state.mode==='advanced'&&!state.shifts.length)return toast('حداقل یک بخش تعریف کن');const btn=$('#solveBtn');btn.disabled=true;$('#solveProgress').style.width='4%';$('#solveText').textContent='در حال امتحان کردن چیدمان‌ها...';await new Promise(r=>setTimeout(r,40));try{const res=KeshikSolver.solve(buildSolverInput(),(p,pen)=>{$('#solveProgress').style.width=p+'%';$('#solveText').textContent=`${p}٪ انجام شد | بهترین جریمه تا اینجا: ${Math.round(pen)}`;});state.assignments=res.assignments;lastPenalty=res.penalty;save();renderSchedule();renderAnalysis();$('#solveText').textContent=`تمام شد | جریمه: ${Math.round(res.penalty)}`;go('schedule');}catch(e){console.error(e);alert('چیدن برنامه با خطا روبه‌رو شد: '+e.message);}finally{btn.disabled=false;}};
function assignmentsByDayShift(){const by={};for(const a of state.assignments)((by[a.day]??={})[a.shiftId]??=[]).push(a);return by;}
function slotMaxForShift(s,role){let m=role==='cover'?Number(s.coverSlots||0):Number(s.mainSlots||0);for(const d of activeDays()){m=Math.max(m,role==='cover'?coverCount(d,s):mainCount(d,s));}return m;}
function renderSchedule(){const box=$('#scheduleTable');if(!state.assignments?.length){box.innerHTML='<div class="notice">هنوز برنامه‌ای ساخته نشده.</div>';return;}const people=Object.fromEntries(state.people.map(p=>[p.id,p.name])),by=assignmentsByDayShift(),shifts=currentShifts(),hol=new Set(effectiveHolidays());let h='<table><thead><tr><th>روز</th><th>روز هفته</th>'+(state.mode==='advanced'?'<th>تعطیل</th>':'')+shifts.map(s=>{if(state.mode==='simple'){const mx=Math.max(1,...activeDays().map(simpleCount));return `<th colspan="${mx}">کشیک</th>`;}return `<th colspan="${Math.max(1,slotMaxForShift(s,'main')+slotMaxForShift(s,'cover'))}">${escHtml(s.name)}</th>`;}).join('')+'</tr></thead><tbody>';for(const d of activeDays()){h+=`<tr><td>${d}</td><td>${week[weekdayForDay(d)]}</td>${state.mode==='advanced'?`<td>${hol.has(d)?'●':''}</td>`:''}`;for(const s of shifts){const arr=(by[d]?.[s.id]||[]);if(state.mode==='simple'){const mx=Math.max(1,...activeDays().map(simpleCount));for(let k=1;k<=mx;k++){if(k>simpleCount(d)){h+='<td class="disabled-slot">—</td>';continue;}const a=arr.find(x=>x.role==='main'&&x.slot===k);h+=`<td>${a?.personId?escHtml(people[a.personId]||'؟'):'<span class="danger">خالی</span>'}</td>`;}}else{const mainMx=slotMaxForShift(s,'main'),coverMx=slotMaxForShift(s,'cover');for(let k=1;k<=mainMx;k++){if(k>mainCount(d,s)){h+='<td class="disabled-slot">—</td>';continue;}const a=arr.find(x=>x.role==='main'&&x.slot===k);h+=`<td>${a?.personId?escHtml(people[a.personId]||'؟'):'<span class="danger">خالی</span>'}</td>`;}for(let k=1;k<=coverMx;k++){if(k>coverCount(d,s)){h+='<td class="disabled-slot">—</td>';continue;}const a=arr.find(x=>x.role==='cover'&&x.slot===k);h+=`<td class="cover-cell"><small>کاور</small><br>${a?.personId?escHtml(people[a.personId]||'؟'):'<span class="danger">خالی</span>'}</td>`;}}}h+='</tr>';}h+='</tbody></table>';box.innerHTML=h;}
function getAnalysis(){if(!state.assignments?.length)return null;return KeshikSolver.analyze(state.assignments,buildSolverInput());}
function hardLabels(r){const a=[];if(r.duplicate)a.push('تکرار در یک روز');if(r.forbidden48)a.push('دو روز پشت‌سرهم');if(r.hardUnavailable)a.push('روز ممنوع');if(r.hardPreferred)a.push('روز ترجیحی');if(r.hardPair)a.push('جفت');if(r.hardAvoid)a.push('جفت‌نشدن');if(r.hardMorning)a.push('مورنینگ');if(r.allowedViol)a.push('بخش مجاز');if(r.outsideRange)a.push('خارج بازه فرد');if(r.maxConsLimit&&r.maxConsSeen>r.maxConsLimit)a.push('روزهای پشت‌سرهم');return a.join('، ');}
function renderAnalysis(){const a=getAnalysis();if(!a){$('#analysisTable').innerHTML='<div class="notice">هنوز برنامه‌ای برای تحلیل نداریم.</div>';return;}$('#anEmpty').textContent=a.empty;$('#anHard').textContent=a.hard;$('#anSoft').textContent=a.soft;$('#anScore').textContent=lastPenalty==null?'-':Math.round(lastPenalty);if(state.mode==='simple'){let h='<table><thead><tr><th>اسم</th><th>تعداد کشیک</th><th>روز ممنوع نقض‌شده</th><th>جفت رعایت‌نشده</th><th>جفت‌نشدن نقض‌شده</th><th>تکرار در روز</th></tr></thead><tbody>';for(const r of a.rows)h+=`<tr><td>${escHtml(r.name)}</td><td>${r.total}</td><td>${r.violatedDays||'—'}</td><td>${r.pairViol}</td><td>${r.avoidViol}</td><td>${r.duplicate?'بله':'خیر'}</td></tr>`;h+='</tbody></table>';$('#analysisTable').innerHTML=h;return;}let h='<table><thead><tr><th>اسم</th><th>کشیک</th><th>تعطیل</th><th>کاور</th>'+state.shifts.map(s=>`<th>${escHtml(s.name)}</th>`).join('')+'<th>دو روز پشت‌سرهم غیرمجاز</th><th>تکرار روز</th><th>جفت رعایت‌نشده</th><th>جفت‌نشدن نقض‌شده</th><th>روز ممنوع نقض‌شده</th><th>خط قرمز نقض‌شده</th><th>مورنینگ بخش</th><th>مورنینگ روز</th><th>جمع مورنینگ</th></tr></thead><tbody>';for(const r of a.rows){h+=`<tr><td>${escHtml(r.name)}</td><td>${r.total}</td><td>${r.holiday}</td><td>${r.cover}</td>${state.shifts.map(s=>`<td>${r.shiftCounts[s.name]||0}</td>`).join('')}<td>${r.forbidden48?'بله':'خیر'}</td><td>${r.duplicate?'بله':'خیر'}</td><td>${r.pairViol}</td><td>${r.avoidViol}</td><td>${r.violatedDays||'—'}</td><td>${hardLabels(r)||'—'}</td><td>${r.morningSection}</td><td>${r.morningDay}</td><td>${r.morning}</td></tr>`;}h+='</tbody></table>';$('#analysisTable').innerHTML=h;}
$('#reanalyze').onclick=()=>{renderAnalysis();go('analysis');};
function scheduleRows(){const people=Object.fromEntries(state.people.map(p=>[p.id,p.name])),by=assignmentsByDayShift(),shifts=currentShifts(),hol=new Set(effectiveHolidays());let headers=['روز','روز هفته'];if(state.mode==='advanced')headers.push('تعطیل');const defs=[];for(const s of shifts){if(state.mode==='simple'){const mx=Math.max(1,...activeDays().map(simpleCount));for(let k=1;k<=mx;k++){headers.push(`کشیک ${k}`);defs.push({s,role:'main',slot:k});}}else{for(let k=1;k<=slotMaxForShift(s,'main');k++){headers.push(`${s.name} اصلی ${k}`);defs.push({s,role:'main',slot:k});}for(let k=1;k<=slotMaxForShift(s,'cover');k++){headers.push(`${s.name} کاور ${k}`);defs.push({s,role:'cover',slot:k});}}}const rows=[headers];for(const d of activeDays()){const row=[d,week[weekdayForDay(d)]];if(state.mode==='advanced')row.push(hol.has(d)?'بله':'');for(const def of defs){const actual=state.mode==='simple'?simpleCount(d):(def.role==='main'?mainCount(d,def.s):coverCount(d,def.s));if(def.slot>actual){row.push('—');continue;}const a=(by[d]?.[def.s.id]||[]).find(x=>x.role===def.role&&x.slot===def.slot);row.push(people[a?.personId]||'');}rows.push(row);}return rows;}
function analysisRows(){const a=getAnalysis();if(!a)return {rows:[[]],styles:[[]]};const header=state.mode==='simple'?['اسم','تعداد کشیک','روزهای ممنوع نقض‌شده','جفت رعایت‌نشده','جفت‌نشدن نقض‌شده','تکرار در روز']:['اسم','تعداد کشیک','کشیک تعطیل','تعداد کاور',...state.shifts.map(s=>`تعداد ${s.name}`),'دو روز پشت‌سرهم غیرمجاز','تکرار در روز','جفت رعایت‌نشده','جفت‌نشدن نقض‌شده','روزهای ممنوع نقض‌شده','خط قرمزهای نقض‌شده','مورنینگ بخش/الگو','مورنینگ روز','جمع مورنینگ'];const rows=[header],styles=[header.map(()=>1)];for(const r of a.rows){const row=state.mode==='simple'?[r.name,r.total,r.violatedDays,r.pairViol,r.avoidViol,r.duplicate?'بله':'خیر']:[r.name,r.total,r.holiday,r.cover,...state.shifts.map(s=>r.shiftCounts[s.name]||0),r.forbidden48?'بله':'خیر',r.duplicate?'بله':'خیر',r.pairViol,r.avoidViol,r.violatedDays,hardLabels(r),r.morningSection,r.morningDay,r.morning];rows.push(row);styles.push(row.map(()=>0));}return {rows,styles};}
$('#exportSchedule').onclick=()=>exportProgram(false);$('#exportAnalysis').onclick=()=>exportProgram(true);function exportProgram(full){if(!state.assignments.length)return toast('اول برنامه را بچین');const sr=scheduleRows(),sheets={'کشیک':{rows:sr,styles:sr.map((r,i)=>r.map(()=>i===0?1:0))}};if(full)sheets['تحلیل']=analysisRows();download(XLSXLite.createWorkbook(sheets),`keshikyar_1_1_${state.year}_${state.month}.xlsx`);}

// وارد کردن اسامی
$('#importFile').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{importedRows=await XLSXLite.readFirstSheet(f);if(!importedRows.length)throw new Error('فایل خالی است');renderMapping(importedRows);$('#mappingBox').classList.remove('hidden');toast('فایل خوانده شد؛ معنی ستون‌ها را بررسی کن');}catch(err){alert('فایل خوانده نشد: '+err.message);}};
const mapIds=['mapName','mapTarget','mapHoliday','mapAllow48','mapUnavailable','mapPreferred','mapTogether','mapAvoid','mapStartDay','mapEndDay','mapPrevMorning','mapAllowedShifts','mapMaxConsecutive','mapPrevShifts','mapPrevHolidays','mapWUnavailable','mapWPreferred','mapWTogether','mapWAvoid','mapWMorning'];
const mapHints={mapName:['نام','اسم','name'],mapTarget:['تعداد کشیک'],mapHoliday:['تعداد کشیک تعطیل'],mapAllow48:['اجازه ۴۸','پشت‌سرهم'],mapUnavailable:['روزهای ممنوع','محدودیت'],mapPreferred:['روزهای ترجیحی'],mapTogether:['جفت با'],mapAvoid:['نباشد با','جفت نشدن'],mapStartDay:['از روز','شروع'],mapEndDay:['تا روز','پایان'],mapPrevMorning:['مورنینگ ماه‌های قبل'],mapAllowedShifts:['بخش‌های مجاز','شیفت‌های مجاز'],mapMaxConsecutive:['حداکثر روز'],mapPrevShifts:['کشیک ماه‌های قبل'],mapPrevHolidays:['کشیک تعطیل ماه‌های قبل'],mapWUnavailable:['اولویت روز ممنوع'],mapWPreferred:['اولویت روز ترجیحی'],mapWTogether:['اولویت جفت'],mapWAvoid:['اولویت جفت نشدن'],mapWMorning:['اولویت مورنینگ']};
function renderMapping(rows){const headers=(rows[0]||[]).map((x,i)=>String(x||`ستون ${i+1}`).trim()||`ستون ${i+1}`);for(const id of mapIds){const sel=$('#'+id);sel.innerHTML=(id==='mapName'?'':'<option value="">انتخاب نشده</option>')+headers.map((h,i)=>`<option value="${i}">${escHtml(h)}</option>`).join('');const found=headers.findIndex(h=>(mapHints[id]||[]).some(k=>h.toLowerCase().includes(k.toLowerCase())));if(found>=0)sel.value=String(found);}const preview=rows.slice(0,7),max=Math.max(...preview.map(r=>r.length));$('#preview').innerHTML='<table><tbody>'+preview.map((r,ri)=>'<tr>'+Array.from({length:max},(_,i)=>`<${ri?'td':'th'}>${escHtml(r[i]??'')}</${ri?'td':'th'}>`).join('')+'</tr>').join('')+'</tbody></table>';applyModeUI();}
$('#doImport').onclick=()=>{if(!importedRows)return;const get=id=>$('#'+id).value===''?null:Number($('#'+id).value),m=Object.fromEntries(mapIds.map(id=>[id,get(id)]));if(m.mapName==null)return toast('ستون نام را انتخاب کن');const val=(r,i)=>i==null?'':r[i],num=(r,i,d=0)=>{if(i==null)return d;const n=Number(latinDigits(val(r,i)));return Number.isFinite(n)&&String(val(r,i)).trim()!==''?n:d;};if(state.seededDemo){state.people=[];state.seededDemo=false;}const pending=[];for(const r of importedRows.slice(1)){const name=String(val(r,m.mapName)||'').trim();if(!name)continue;const p=newPerson({name});if(state.mode==='advanced'){p.targetShifts=num(r,m.mapTarget,0);p.targetHolidays=num(r,m.mapHoliday,0);p.allow48=m.mapAllow48==null?false:truthy(val(r,m.mapAllow48));p.preferredDays=parseDays(val(r,m.mapPreferred));p.startDay=num(r,m.mapStartDay,1)||1;p.endDay=num(r,m.mapEndDay,daysInMonth())||daysInMonth();p.previousMorning=num(r,m.mapPrevMorning,0);p.maxConsecutiveDays=num(r,m.mapMaxConsecutive,0);p.previousShifts=num(r,m.mapPrevShifts,0);p.previousHolidays=num(r,m.mapPrevHolidays,0);p.ruleWeights={unavailable:m.mapWUnavailable==null||String(val(r,m.mapWUnavailable)).trim()===''?null:clampWeight(num(r,m.mapWUnavailable)),preferred:m.mapWPreferred==null||String(val(r,m.mapWPreferred)).trim()===''?null:clampWeight(num(r,m.mapWPreferred)),together:m.mapWTogether==null||String(val(r,m.mapWTogether)).trim()===''?null:clampWeight(num(r,m.mapWTogether)),avoid:m.mapWAvoid==null||String(val(r,m.mapWAvoid)).trim()===''?null:clampWeight(num(r,m.mapWAvoid)),morning:m.mapWMorning==null||String(val(r,m.mapWMorning)).trim()===''?null:clampWeight(num(r,m.mapWMorning))};}p.unavailableDays=parseDays(val(r,m.mapUnavailable));pending.push({p,together:splitNames(val(r,m.mapTogether)),avoid:splitNames(val(r,m.mapAvoid)),allowed:splitNames(val(r,m.mapAllowedShifts))});}
  for(const x of pending){let p=state.people.find(q=>q.name.trim()===x.p.name);if(!p){p=x.p;state.people.push(p);}else Object.assign(p,x.p);}for(const x of pending){const p=state.people.find(q=>q.name.trim()===x.p.name);p.togetherIds=x.together.map(n=>state.people.find(q=>q.name.trim()===n)?.id).filter(Boolean);p.avoidIds=x.avoid.map(n=>state.people.find(q=>q.name.trim()===n)?.id).filter(Boolean);p.allowedShiftIds=x.allowed.map(n=>state.shifts.find(s=>s.name.trim()===n)?.id).filter(Boolean);}normalizePeopleLinks();state.assignments=[];save();renderPeople();go('people');toast(`${pending.length} نفر وارد شد`);
};

// تحلیل Excel آماده
const analysisOptionDefs=[['total','تعداد کل کشیک'],['holiday','کشیک تعطیل'],['section','تعداد هر بخش'],['cover','تعداد کاور'],['consecutive','دو روز پشت‌سرهم / ۴۸ی'],['duplicate','تکرار در یک روز'],['together','جفت'],['avoid','جفت‌نشدن'],['limits','روزهای ممنوع'],['morning','مورنینگ']];
function renderAnalysisChoices(){const box=$('#analysisChoices');box.innerHTML=analysisOptionDefs.map(([k,t])=>`<label class="choice-chip"><input type="checkbox" data-analysis-choice="${k}" checked> ${t}</label>`).join('');}
renderAnalysisChoices();
$('#analysisExcelFile').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{externalRows=await XLSXLite.readFirstSheet(f);if(!externalRows.length)throw new Error('فایل خالی است');renderExternalColumnMap(externalRows);$('#analysisExcelSetup').classList.remove('hidden');externalReport=null;$('#exportExcelAnalysis').disabled=true;}catch(err){alert('فایل خوانده نشد: '+err.message);}};
function guessColumnRole(h){const x=String(h||'').toLowerCase();if(/(^|\s)(روز|تاریخ|date)/.test(x))return 'day';if(/روز هفته|weekday|هفته/.test(x))return 'weekday';if(/تعطیل|holiday/.test(x))return 'holiday';if(/مورنینگ روز/.test(x))return 'morningday';return 'schedule';}
function renderExternalColumnMap(rows){const headers=rows[0]||[];let h='<table><thead><tr><th>ستون</th><th>نمونه</th><th>این ستون چیست؟</th><th>نام بخش</th><th>نوع جایگاه</th><th>مورنینگ این بخش</th></tr></thead><tbody>';headers.forEach((head,i)=>{const role=guessColumnRole(head),sample=rows.slice(1,5).map(r=>r[i]).filter(Boolean)[0]||'';h+=`<tr data-ext-col="${i}"><td>${escHtml(head||`ستون ${i+1}`)}</td><td>${escHtml(sample)}</td><td><select data-ext-role><option value="ignore">نادیده بگیر</option><option value="day" ${role==='day'?'selected':''}>شماره روز / تاریخ</option><option value="weekday" ${role==='weekday'?'selected':''}>روز هفته</option><option value="holiday" ${role==='holiday'?'selected':''}>تعطیل بودن</option><option value="morningday" ${role==='morningday'?'selected':''}>مورنینگ روز</option><option value="schedule" ${role==='schedule'?'selected':''}>ستون کشیک</option></select></td><td><input data-ext-section value="${role==='schedule'?escAttr(String(head||`بخش ${i+1}`).replace(/\s+(اصلی|کاور)\s*\d*$/,'')):''}"></td><td><select data-ext-slot-role><option value="main">اصلی</option><option value="cover" ${/کاور/.test(String(head))?'selected':''}>کاور</option></select></td><td><input type="checkbox" data-ext-morning></td></tr>`;});h+='</tbody></table>';$('#analysisColumnMap').innerHTML=h;const preview=rows.slice(0,8),max=Math.max(...preview.map(r=>r.length));$('#analysisExcelPreview').innerHTML='<h4>پیش‌نمایش فایل</h4><table><tbody>'+preview.map((r,ri)=>'<tr>'+Array.from({length:max},(_,i)=>`<${ri?'td':'th'}>${escHtml(r[i]??'')}</${ri?'td':'th'}>`).join('')+'</tr>').join('')+'</tbody></table>';}
function externalConfig(){const cols=$$('[data-ext-col]').map(tr=>({index:Number(tr.dataset.extCol),role:tr.querySelector('[data-ext-role]').value,section:tr.querySelector('[data-ext-section]').value.trim(),slotRole:tr.querySelector('[data-ext-slot-role]').value,morning:tr.querySelector('[data-ext-morning]').checked}));const choices=new Set($$('[data-analysis-choice]:checked').map(x=>x.dataset.analysisChoice));return {cols,choices};}
function parseDayValue(v,fallback){const s=latinDigits(v).trim();const parts=s.match(/\d+/g)||[];if(parts.length>=2){const n=Number(parts[parts.length-1]);if(n>=1&&n<=31)return n;}const n=Number(s);if(Number.isFinite(n)){if(n>=1&&n<=31)return n;if(n>1000&&n<70000){const dt=new Date(Date.UTC(1899,11,30)+n*86400000);return dt.getUTCDate();}}const first=parseInt(s);return Number.isFinite(first)?first:fallback;}
function buildExternalAnalysis(){
  const cfg=externalConfig(),dayCol=cfg.cols.find(c=>c.role==='day');if(!dayCol)throw new Error('حداقل یک ستون را به عنوان شماره روز / تاریخ مشخص کن');const schedCols=cfg.cols.filter(c=>c.role==='schedule');if(!schedCols.length)throw new Error('حداقل یک ستون کشیک مشخص کن');
  const holidayCol=cfg.cols.find(c=>c.role==='holiday'),morningDayCol=cfg.cols.find(c=>c.role==='morningday');const names=new Set();const rawAssignments=[];const holidays=new Set(),dayCfg={};let seq=0;
  for(const row of externalRows.slice(1)){const day=parseDayValue(row[dayCol.index],null);if(!day)continue;if(holidayCol&&truthy(row[holidayCol.index]))holidays.add(day);if(morningDayCol&&truthy(row[morningDayCol.index])){dayCfg[day]??={};dayCfg[day].morningRisk=true;}for(const c of schedCols){for(const name of splitNames(row[c.index])){names.add(name);rawAssignments.push({day,section:c.section||`بخش ${c.index+1}`,role:c.slotRole,morning:c.morning,name,seq:++seq});}}}
  if(!holidayCol)effectiveHolidays().forEach(d=>holidays.add(d));const existingByName=Object.fromEntries(state.people.map(p=>[p.name.trim(),p]));const people=[...names].map(name=>existingByName[name]?{...existingByName[name]}:newPerson({name,allow48:true,startDay:1,endDay:31}));const byName=Object.fromEntries(people.map(p=>[p.name.trim(),p]));const sectionNames=[...new Set(schedCols.map(c=>c.section||`بخش ${c.index+1}`))],shifts=sectionNames.map(name=>({id:'ext_'+uid(),name,mainSlots:0,coverSlots:0,morningRisk:schedCols.some(c=>(c.section||`بخش ${c.index+1}`)===name&&c.morning),startDay:1,endDay:31})),shiftByName=Object.fromEntries(shifts.map(s=>[s.name,s]));const slotCounter={};const assignments=rawAssignments.map(a=>{const key=`${a.day}:${a.section}:${a.role}`;slotCounter[key]=(slotCounter[key]||0)+1;return {day:a.day,shiftId:shiftByName[a.section].id,shiftName:a.section,role:a.role,slot:slotCounter[key],personId:byName[a.name].id};});
  const input={people,globalRuleWeights:{...state.globalRuleWeights},shifts,dayConfig:dayCfg,weeklyMorning:{},daysInMonth:31,periodStart:1,periodEnd:31,holidays:[...holidays],weekdays:Array.from({length:32},(_,d)=>d?weekdayForDay(Math.min(d,daysInMonth())):0),runs:1};const report=KeshikSolver.analyze(assignments,input);return {report,input,assignments,choices:cfg.choices};
}
function externalReportRows(bundle){const {report,input,choices}=bundle;const header=['اسم'];if(choices.has('total'))header.push('تعداد کشیک');if(choices.has('holiday'))header.push('کشیک تعطیل');if(choices.has('section'))input.shifts.forEach(s=>header.push(`تعداد ${s.name}`));if(choices.has('cover'))header.push('تعداد کاور');if(choices.has('consecutive'))header.push('دو روز پشت‌سرهم غیرمجاز');if(choices.has('duplicate'))header.push('تکرار در یک روز');if(choices.has('together'))header.push('جفت رعایت‌نشده');if(choices.has('avoid'))header.push('جفت‌نشدن نقض‌شده');if(choices.has('limits'))header.push('روزهای ممنوع نقض‌شده');if(choices.has('morning'))header.push('جمع مورنینگ');const rows=[header];for(const r of report.rows){const row=[r.name];if(choices.has('total'))row.push(r.total);if(choices.has('holiday'))row.push(r.holiday);if(choices.has('section'))input.shifts.forEach(s=>row.push(r.shiftCounts[s.name]||0));if(choices.has('cover'))row.push(r.cover);if(choices.has('consecutive'))row.push(r.consecutive?'بله':'خیر');if(choices.has('duplicate'))row.push(r.duplicate?'بله':'خیر');if(choices.has('together'))row.push(r.pairViol);if(choices.has('avoid'))row.push(r.avoidViol);if(choices.has('limits'))row.push(r.violatedDays);if(choices.has('morning'))row.push(r.morning);rows.push(row);}return rows;}
$('#runExcelAnalysis').onclick=()=>{try{externalReport=buildExternalAnalysis();const rows=externalReportRows(externalReport);$('#externalAnalysisResult').innerHTML='<h4>نتیجه تحلیل</h4><table><tbody>'+rows.map((r,ri)=>'<tr>'+r.map(x=>`<${ri?'td':'th'}>${escHtml(x??'')}</${ri?'td':'th'}>`).join('')+'</tr>').join('')+'</tbody></table>';$('#exportExcelAnalysis').disabled=false;toast('تحلیل انجام شد');}catch(err){alert(err.message);}};
$('#exportExcelAnalysis').onclick=()=>{if(!externalReport)return;const rows=externalReportRows(externalReport);download(XLSXLite.createWorkbook({'تحلیل Excel':{rows,styles:rows.map((r,i)=>r.map(()=>i===0?1:0))}}),'keshikyar_excel_analysis.xlsx');};

// پشتیبان و داشبورد
$('#backupBtn').onclick=()=>download(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),`keshikyar_1_1_backup_${state.year}_${state.month}.json`);$('#restoreFile').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{state=migrateState(JSON.parse(await f.text()));selectedPeople.clear();save();renderAll();toast('پشتیبان برگشت');}catch(err){alert('پشتیبان معتبر نیست');}};$('#resetBtn').onclick=()=>{if(confirm('همه اطلاعات پاک شود؟')){for(const k of ['keshikYarV11','keshikPlannerV1Milad98','keshikPlannerV2','keshikPlannerV1'])localStorage.removeItem(k);state=defaultState();selectedPeople.clear();selectedCalendarDay=1;lastPenalty=null;save();renderAll();}};
function renderDashboard(){const active=state.people.filter(p=>p.active).length;$('#dashPeople').textContent=active;$('#dashDays').textContent=activeDays().length;$('#dashSlots').textContent=totalSlots();$('#dashStatus').textContent=state.assignments?.length?'برنامه آماده است':'هنوز چیده نشده';}
function renderAll(){applyModeUI();renderGlobalPriorities();renderPeople();renderShifts();renderCalendar();renderSchedule();renderAnalysis();renderDashboard();$('#jy').value=state.year;$('#jm').value=state.month;$('#fridaysHoliday').value=state.fridaysHoliday?'1':'0';$('#calendarMode').value=state.calendarMode;$('#manualDays').value=state.manualDays;$('#manualStartWeek').value=state.manualStartWeek;$('#periodStart').value=periodBounds().start;$('#periodEnd').value=periodBounds().end;$('#simpleDailyPeople').value=state.simpleDailyPeople;}
renderAll();
