(function(global){
  const te=new TextEncoder(), td=new TextDecoder('utf-8');
  const u16=(v)=>new Uint8Array([v&255,(v>>>8)&255]);
  const u32=(v)=>new Uint8Array([v&255,(v>>>8)&255,(v>>>16)&255,(v>>>24)&255]);
  function concat(parts){let n=parts.reduce((s,p)=>s+p.length,0),o=new Uint8Array(n),k=0;for(const p of parts){o.set(p,k);k+=p.length;}return o;}
  const crcTable=(()=>{let t=[];for(let n=0;n<256;n++){let c=n;for(let k=0;k<8;k++)c=(c&1)?0xedb88320^(c>>>1):c>>>1;t[n]=c>>>0;}return t;})();
  function crc32(bytes){let c=0xffffffff;for(const b of bytes)c=crcTable[(c^b)&255]^(c>>>8);return (c^0xffffffff)>>>0;}
  function esc(s){return String(s??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&apos;');}
  function colName(n){let s='';while(n>=0){s=String.fromCharCode(65+n%26)+s;n=Math.floor(n/26)-1;}return s;}
  function zipStore(files){let locals=[],centrals=[],offset=0;const now=new Date();const dostime=((now.getHours()&31)<<11)|((now.getMinutes()&63)<<5)|((Math.floor(now.getSeconds()/2))&31);const dosdate=(((now.getFullYear()-1980)&127)<<9)|(((now.getMonth()+1)&15)<<5)|(now.getDate()&31);
    for(const [name,data0] of Object.entries(files)){const nameB=te.encode(name),data=typeof data0==='string'?te.encode(data0):data0,crc=crc32(data);
      const local=concat([u32(0x04034b50),u16(20),u16(0),u16(0),u16(dostime),u16(dosdate),u32(crc),u32(data.length),u32(data.length),u16(nameB.length),u16(0),nameB,data]);locals.push(local);
      const central=concat([u32(0x02014b50),u16(20),u16(20),u16(0),u16(0),u16(dostime),u16(dosdate),u32(crc),u32(data.length),u32(data.length),u16(nameB.length),u16(0),u16(0),u16(0),u16(0),u32(0),u32(offset),nameB]);centrals.push(central);offset+=local.length;
    }
    const cdir=concat(centrals), localAll=concat(locals), eocd=concat([u32(0x06054b50),u16(0),u16(0),u16(centrals.length),u16(centrals.length),u32(cdir.length),u32(localAll.length),u16(0)]);return new Blob([localAll,cdir,eocd],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'});
  }
  function sheetXml(rows, styles){let out=['<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetViews><sheetView workbookViewId="0" rightToLeft="1"/></sheetViews><sheetData>'];
    rows.forEach((row,ri)=>{out.push(`<row r="${ri+1}">`);row.forEach((v,ci)=>{if(v===undefined||v===null||v==='')return;const ref=colName(ci)+(ri+1);const st=styles?.[ri]?.[ci]||0;if(typeof v==='number'&&Number.isFinite(v))out.push(`<c r="${ref}"${st?` s="${st}"`:''}><v>${v}</v></c>`);else out.push(`<c r="${ref}" t="inlineStr"${st?` s="${st}"`:''}><is><t xml:space="preserve">${esc(v)}</t></is></c>`);});out.push('</row>');});
    out.push('</sheetData></worksheet>');return out.join('');
  }
  function createWorkbook(sheets){const names=Object.keys(sheets);const files={};files['[Content_Types].xml']='<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/>'+names.map((_,i)=>`<Override PartName="/xl/worksheets/sheet${i+1}.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>`).join('')+'</Types>';
    files['_rels/.rels']='<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>';
    files['xl/workbook.xml']='<?xml version="1.0" encoding="UTF-8" standalone="yes"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets>'+names.map((n,i)=>`<sheet name="${esc(n.slice(0,31))}" sheetId="${i+1}" r:id="rId${i+1}"/>`).join('')+'</sheets></workbook>';
    files['xl/_rels/workbook.xml.rels']='<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'+names.map((_,i)=>`<Relationship Id="rId${i+1}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet${i+1}.xml"/>`).join('')+`<Relationship Id="rId${names.length+1}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>`;
    files['xl/styles.xml']='<?xml version="1.0" encoding="UTF-8" standalone="yes"?><styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><fonts count="2"><font><sz val="11"/><name val="Calibri"/></font><font><b/><sz val="11"/><name val="Calibri"/></font></fonts><fills count="6"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FFFFCCCC"/><bgColor indexed="64"/></patternFill></fill><fill><patternFill patternType="solid"><fgColor rgb="FFCCFFCC"/><bgColor indexed="64"/></patternFill></fill><fill><patternFill patternType="solid"><fgColor rgb="FFFFFF99"/><bgColor indexed="64"/></patternFill></fill><fill><patternFill patternType="solid"><fgColor rgb="FFFFCC80"/><bgColor indexed="64"/></patternFill></fill></fills><borders count="1"><border/></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="6"><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/><xf numFmtId="0" fontId="1" fillId="0" borderId="0" xfId="0" applyFont="1"/><xf numFmtId="0" fontId="0" fillId="2" borderId="0" xfId="0" applyFill="1"/><xf numFmtId="0" fontId="0" fillId="3" borderId="0" xfId="0" applyFill="1"/><xf numFmtId="0" fontId="0" fillId="4" borderId="0" xfId="0" applyFill="1"/><xf numFmtId="0" fontId="0" fillId="5" borderId="0" xfId="0" applyFill="1"/></cellXfs></styleSheet>';
    names.forEach((n,i)=>{files[`xl/worksheets/sheet${i+1}.xml`]=sheetXml(sheets[n].rows,sheets[n].styles);});return zipStore(files);
  }
  async function unzipEntries(file){const b=new Uint8Array(await file.arrayBuffer()), dv=new DataView(b.buffer);let e=-1;for(let i=b.length-22;i>=0&&i>b.length-70000;i--){if(dv.getUint32(i,true)===0x06054b50){e=i;break;}}if(e<0)throw new Error('ZIP/XLSX نامعتبر');const count=dv.getUint16(e+10,true), cOff=dv.getUint32(e+16,true);let p=cOff, entries={};for(let k=0;k<count;k++){if(dv.getUint32(p,true)!==0x02014b50)break;const method=dv.getUint16(p+10,true),comp=dv.getUint32(p+20,true),nameLen=dv.getUint16(p+28,true),extra=dv.getUint16(p+30,true),comment=dv.getUint16(p+32,true),localOff=dv.getUint32(p+42,true),name=td.decode(b.slice(p+46,p+46+nameLen));const ln=dv.getUint16(localOff+26,true),le=dv.getUint16(localOff+28,true),dataStart=localOff+30+ln+le, compressed=b.slice(dataStart,dataStart+comp);let data;if(method===0)data=compressed;else if(method===8){if(typeof DecompressionStream==='undefined')throw new Error('مرورگر شما DecompressionStream را پشتیبانی نمی‌کند. از Edge/Chrome جدید استفاده کنید.');const ds=new DecompressionStream('deflate-raw');data=new Uint8Array(await new Response(new Blob([compressed]).stream().pipeThrough(ds)).arrayBuffer());}else throw new Error('Compression method پشتیبانی نمی‌شود: '+method);entries[name]=data;p+=46+nameLen+extra+comment;}return entries;}
  async function readFirstSheet(file){const ext=file.name.toLowerCase().split('.').pop();if(ext==='csv'){const text=await file.text();return parseCSV(text);}const entries=await unzipEntries(file);let shared=[];if(entries['xl/sharedStrings.xml']){const doc=new DOMParser().parseFromString(td.decode(entries['xl/sharedStrings.xml']),'application/xml');shared=[...doc.getElementsByTagName('si')].map(si=>[...si.getElementsByTagName('t')].map(t=>t.textContent||'').join(''));}
    let sheetPath='xl/worksheets/sheet1.xml';if(!entries[sheetPath]){sheetPath=Object.keys(entries).find(x=>x.startsWith('xl/worksheets/sheet')&&x.endsWith('.xml'));}if(!sheetPath)throw new Error('Worksheet پیدا نشد');const doc=new DOMParser().parseFromString(td.decode(entries[sheetPath]),'application/xml');const rows=[];for(const r of [...doc.getElementsByTagName('row')]){const arr=[];for(const c of [...r.getElementsByTagName('c')]){const ref=c.getAttribute('r')||'',letters=(ref.match(/[A-Z]+/)||['A'])[0];let ci=0;for(const ch of letters)ci=ci*26+(ch.charCodeAt(0)-64);ci--;const t=c.getAttribute('t');let val='';if(t==='inlineStr')val=[...c.getElementsByTagName('t')].map(x=>x.textContent||'').join('');else{const v=c.getElementsByTagName('v')[0]?.textContent??'';if(t==='s')val=shared[Number(v)]??v;else if(t==='b')val=v==='1'?'TRUE':'FALSE';else val=v;}arr[ci]=val;}rows.push(arr);}return rows;}
  function parseCSV(text){const rows=[];let row=[],cell='',q=false;for(let i=0;i<text.length;i++){const ch=text[i];if(q){if(ch==='"'&&text[i+1]==='"'){cell+='"';i++;}else if(ch==='"')q=false;else cell+=ch;}else{if(ch==='"')q=true;else if(ch===','){row.push(cell);cell='';}else if(ch==='\n'){row.push(cell.replace(/\r$/,''));rows.push(row);row=[];cell='';}else cell+=ch;}}row.push(cell);if(row.some(x=>x!==''))rows.push(row);return rows;}
  global.XLSXLite={createWorkbook,readFirstSheet};
})(window);
